[tool.poetry]
name = "otus-basic-homeworks"
version = "0.1.0"
description = ""
authors = ["ka4en3"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
pydentic = "^0.0.1.dev3"
jinja2 = "^3.1.4"
black = "^25.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
